aligent/cdk-stacks

packages/serverless-deploy-iam/bin/app.ts

Here, `lambda:PutFunctionConcurrency` action is included in the service role. 
This is required when we are setting `Reserved concurrency` with lambda.

Allow lambda:PutFunctionConcurrency action

---

packages/serverless-deploy-iam/bin/app.ts

It has been identified that some of the services required `lambda tag resources` permission.

Include lambda tag resources action to service role

---

packages/serverless-deploy-iam/bin/app.ts

This PR adds the `sns:ListSubscriptionsByTopic` and `sns:Unsubscribe` so topic subscriptions can be added/removed in Cloudformation inside the serverless.yml.
E.g. Currently changing this:
```yaml
SNSFailedTasksTopic:
Type: AWS::SNS::Topic
Properties:
Subscription:
- Endpoint: ${self:custom.failure_alarm_email_to}
Protocol: email
```
to just this:
```yaml
SNSFailedTasksTopic:
Type: AWS::SNS::Topic
```
Throws a permissions error.

Add SNS Permissions

---

packages/serverless-deploy-iam/bin/app.ts

`DescribeLogGroup` is not valid `DescribeLogGroups` is :slightly_smiling_face:

DO-1382: Fix typo

---

packages/serverless-deploy-iam/package-lock.json

@gowrizrh this was removed in #9 but is required for an `npm ci` (which liftoff uses to initialise the serverless iam user)

Add package-lock.json

---

packages/serverless-deploy-iam/bin/app.ts
packages/serverless-deploy-iam/test/deploy-role.test.ts

Add the service name as a default CloudWatch permission.
This will allow developers to create custom log groups prefixed with the service name. 
`DO-1418`

Add service name to log group permissions

---

packages/serverless-deploy-iam/bin/app.ts
packages/serverless-deploy-iam/test/deploy-role.test.ts

Resource delimiters were set to `/` for most resources. This should not be the case. 
I've corrected this to set the delimiter to a blank space for the resources that require one.
The Lambda qualifier was also missing a colon.

Fix resource delimiters

---

packages/serverless-deploy-iam/bin/app.ts

When updating a CDK parameter this doesn’t create a CloudFormation change set. 
To get around this we create a hash of the parameters and add this to the end of the IAM policy. This forces a deployment when parameters change.

Force redeploy on parameter change

---

packages/serverless-deploy-iam/bin/app.ts

This should fix the bug of shared vpc not being added. 
`sharedVPCParameter.valueAsString` doesn't work as parameters are not resolved during deployment time.

Add enable vpc permissions env var

---

packages/serverless-deploy-iam/bin/app.ts

Adds the permission to create users in IAM. This is useful for when a service needs to create an IAM access key and secret for use by a third party.

feat: add create user permissions

---

packages/serverless-deploy-iam/bin/app.ts

I should have picked this up before... We need to run user related actions on users, not roles.

fix: move user actions to user prefix

---

packages/serverless-deploy-iam/bin/app.ts

Serverless Stack started using AWS EventBridge Scheduler Schedule group feature. This change will grant the deloy role the permission to use the feature.

add schedule-group permissions to IAM deploy role policy

---

packages/serverless-deploy-iam/bin/app.ts

- allow * to lambda:CreateEventSourceMapping
- allow lambda:DeleteFunctionConcurrency for failed CFN deployment role-back

additional serverless deploy permissions

---

packages/serverless-deploy-iam/bin/app.ts

Provide deploy user with `lambda:DeleteEventSourceMapping` privilege to allow for event source map renaming in Lambda functions.
This permission is already granted to the Role but the defined ARM format does not provide sufficient coverage.

Renaming Even Source Mappings is not possible without DELETE

---

packages/serverless-deploy-iam/bin/app.ts

When you are wanting to tag an SNS Topic upon creation you are required to have the `:sns:TagResource` permissions.
This seems to happen when you refer to a topic by environment reference.
**References:**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-tags
an SNS Topic
https://docs.aws.amazon.com/sns/latest/api/API_TagResource.html

Allow the deploy user to tag SNS topics.

---

packages/serverless-deploy-iam/bin/app.ts

Make KMS use the default behaviour of a slash. 
The resource arn looks like: `arn:aws:kms:ap-southeast-2:999999999999:keyclient-int*`
When it should look like: `arn:aws:kms:ap-southeast-2:999999999999:key/client-int*`

fix: add slash to kms qualifier

---

packages/serverless-deploy-iam/bin/app.ts

KMS keys ARNs are formed using their IDs which is randomly generated. Unfortunately that means we can't lock them down by a qualifier :disappointed: 
This grants access to all keys within the account.

fix: grant access to all kms keys for that account

---

packages/serverless-deploy-iam/bin/app.ts

This PR attemp to fix the `Stage already exists` issue when enabling tracing in API gateway and will potentially fix other issues related to API Gateway if it:
- hasTracingConfigured
- hasMetricsConfigured
- hasLogsConfigured
- hasTagsConfigured
For more details on how this happens, please check the attached file: 
[UB Subscription Webapp Deployment Retro.md](https://github.com/aligent/cdk-stacks/files/14676020/UB.Subscription.Webapp.Deployment.Retro.md)

Allow deploy user to get ApiGateway stages

---

packages/serverless-deploy-iam/bin/app.ts
packages/serverless-deploy-iam/test/deploy-role.test.ts

Adding to support CloudWatch log masking deployment through serverless: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data.html

fix: add iam update policy permissions

---

packages/serverless-deploy-iam/bin/app.ts

Adds permission to tag DynamoDB resources. 
Serverless seems to be automatically tagging DynamoDB tables so we need this now :(

feat: add tag permissions for dynamo

---

packages/serverless-deploy-iam/bin/app.ts

Serverless now requires the ability to tag roles.
This adds TagRole and UntagRole to the IAM block in app.ts

FIX: Added TagRole required by serverless

---

packages/serverless-deploy-iam/bin/app.ts

We were missing the permissions to update and describe the ttl. This adds it :man_dancing:

feat: add ttl permission

---

packages/serverless-deploy-iam/bin/app.ts

Removed invalid action.
Changed default from a blank string to the parameter hash. This was causing deployments to fail.

fix: add parameter hash as default value

---

packages/serverless-deploy-iam/bin/app.ts

API GW / Serverless changed at some point and now it needs GET access across the entire `restapis`, rather than just `stages` or `deployments`. At this point it seems much easier to just allow the whole API GW service through for the deploy user. 
Happy to hear any alternatives though.

feat: compress api gateway permissions

---

packages/serverless-deploy-iam/bin/app.ts

This is a big issue with serverless apparently needing to create a role however the way we handle deployments to CloudFormation for serverless requires these permissions on our deploy user rather than typical serverless yaml.
Here is an example of the approach that is used from a serverless POV however for us it will be in IAM instead.
[Caller does not have permissions to create a Service Linked Role](https://github.com/amplify-education/serverless-domain-manager/issues/112#issuecomment-455357953)

Allow Serverless to create linked role

---

packages/serverless-deploy-iam/bin/app.ts

To address Serverless error of "Caller does not have permissions to create a Service Linked Role."

add iam:CreateServiceLinkedRole to allow API GW custom domain creation

---

packages/serverless-deploy-iam/bin/app.ts

I'm not sure how this wasn't here already? - Maybe I'm missing something :thinking: 
Deploy fails as it can't create the deploy bucket:

feat: add create bucket
